      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g @ionic/cli @capacitor/core @capacitor/cli

      - name: Build Web Project
        run: npm run build --if-present

      - name: Sync Capacitor
        run: npx cap sync
